[project]
name = "project-2-sirotkin-m26-555"
version = "0.1.0"
description = ""
authors = [
    {name = "sush1",email = "pavelsirotkin17@yandex.ru"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "prettytable>=3.18.0",
    "prompt>=0.4.1,<0.5.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1,<10.0.0",
    "ruff>=0.16.8,<0.17.0",
]

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "src"
module-root = ""

[project.scripts]
project = "src.primitive_db.main:main"
database = "src.primitive_db.main:main"

[tool.ruff]
line-length = 88
target-version = "py312"
exclude = ["venv", ".venv", "dist", "__pycache__"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
